### ISSUE TITLE
Templ has native support for hot-reload with browser refresh ;)

### ISSUE THREAD

**Issue by algoflows** [TomDoesTech/GOTTH#1]
https://github.com/TomDoesTech/GOTTH/blob/79e0095f83dc7f1af6a13197cbe4859b767c9211/Makefile#L14

Hot reload with templ is possible which reloads the tab when changes, I believe that mitigates the need for air.

https://templ.guide/commands-and-tools/hot-reload#built-in

templ generate --watch --proxy="http://localhost:8080" --cmd="go run ."

**Comment by tomanagle** [comment]
Oh cool, I'll add it in. Or you can make a PR

**Comment by markkhoo** [comment]
According to [templ docs on hot reload](https://templ.guide/commands-and-tools/hot-reload/#alternative-2-air) we could add it to air's configuration? They say air's reload performance than templ's built-in one.

**Comment by markkhoo** [comment]
made a PR for it: #2

**Comment by markkhoo** [comment]
I made a PR for it: #3
