### ISSUE TITLE
Safari not rendering webpage

### ISSUE THREAD

**Issue by sevriugin** [TomDoesTech/GOTTH#12]
The Safari not rendering page as return content type is not right, fixed adding `;` between `text/html` and `charset=utf-8` in 
```go
w.Header().Set("Content-Type", "text/html; charset=utf-8")
```

**Comment by tomanagle** [comment]
Do you want to make a PR?

**Comment by vjal** [comment]
I ran into this same issue and opened pr with a fix #18
