### ISSUE TITLE
Bug: When user is logging out the guestIndex template is served inside nav element.

### ISSUE THREAD

**Issue by zacharyad** [TomDoesTech/GOTTH#24]
## Issue Explanation
When logging out the guestIndex template is sent to the nav element where the logout button was clicked and posted to the /loggout route.

<img width="1435" alt="Screenshot 2024-05-23 at 3 22 18 PM" src="https://github.com/TomDoesTech/GOTTH/assets/29681485/bb2af963-84ad-4cbb-afdc-dd8be477daf5">
<img width="1437" alt="Screenshot 2024-05-23 at 3 22 33 PM" src="https://github.com/TomDoesTech/GOTTH/assets/29681485/0a7bf684-019d-483a-95c4-5de201bcdbba">

https://github.com/TomDoesTech/GOTTH/blob/b3c6f5aef3f0263eebc77c07ba9e4e889b4a135d/internal/templates/layout.templ#L41

## Proposed fix 
i wanted to make an issue before submitting a PR. here is [ link ](https://github.com/zacharyad/GOTTH/blob/main/internal/templates/layout.templ) to my forked repo with the fix in main branch at internal/templates/layout.templ (line #41)

I am new to golang and htmx (and contributing to open source for that matter) so would welcome feedback on the above fix on my forked branch and any other advice you have for the future.

**Comment by tomanagle** [comment]
Thanks @zacharyad, can you please open the PR?
