### ISSUE TITLE
Remove tailwind binary from repo?

### ISSUE THREAD

**Issue by distek** [TomDoesTech/GOTTH#7]
Hello!

I was having issues with the cloning of this repo. Cloning was failing/taking entirely way to long. I ended up needing to download a zip of the repo (which was 19MB zipped, ~46M unzipped)

Is there a reason for including the `tailwindcss` binary within the repo itself? There's instructions within the readme already for acquiring the tailwind cli, and the binary is 45MB.

There _might_ also be some legal implications regarding redistribution that may be of concern as well (I haven't reviewed TWs license).

Otherwise, excited to start using this stack!

Thanks!

**Comment by tomanagle** [comment]
Yeah, good idea. I'll remove it and update the readme

**Comment by tomanagle** [comment]
I removed the binary. I'll update the readme with more clear instructions
